#ifndef HELIX_CONFIG_H
#define HELIX_CONFIG_H

#include <stddef.h>
#include <stdint.h>

#define HELIX_RS_N 255
#define HELIX_RS_K 223
#define HELIX_RS_T (HELIX_RS_N - HELIX_RS_K)
#define HELIX_RS_MAX_ERR (HELIX_RS_T / 2)

#define HELIX_MAGIC_V1 "HELIX01"
#define HELIX_MAGIC_V2 "HELIX02"
#define HELIX_MAGIC_V3 "HELIX03"
#define HELIX_MAGIC_V4 "HELIX04"
#define HELIX_MAGIC_V5 "HELIX05"
#define HELIX_MAGIC HELIX_MAGIC_V5
#define HELIX_HEADER_V1_SIZE 32
#define HELIX_HEADER_V2_SIZE 40
#define HELIX_HEADER_V3_SIZE 64
#define HELIX_HEADER_V4_SIZE 80
#define HELIX_HEADER_V5_SIZE 96
#define HELIX_HEADER_SIZE HELIX_HEADER_V5_SIZE

#define HELIX_OLIGO_INDEX_BYTES 4
#define HELIX_OLIGO_LENGTH_BYTES 2
#define HELIX_OLIGO_CONSTRAINT_SEED_BYTES 1
#define HELIX_V4_OLIGO_META_BYTES (HELIX_OLIGO_INDEX_BYTES + HELIX_OLIGO_LENGTH_BYTES)
#define HELIX_V4_OLIGO_PAYLOAD_BYTES (HELIX_RS_K - HELIX_V4_OLIGO_META_BYTES)
#define HELIX_OLIGO_META_BYTES (HELIX_OLIGO_INDEX_BYTES + HELIX_OLIGO_LENGTH_BYTES + HELIX_OLIGO_CONSTRAINT_SEED_BYTES)
#define HELIX_OLIGO_PAYLOAD_BYTES (HELIX_RS_K - HELIX_OLIGO_META_BYTES)
#define HELIX_OLIGO_DNA_CHARS (HELIX_RS_N * 4)
#define HELIX_OLIGO_LINE_CHARS (HELIX_OLIGO_DNA_CHARS + 1)
#define HELIX_PARITY_STRIPE_DATA_OLIGOS 8U
#define HELIX_PARITY_STRIPE_PARITY_OLIGOS 2U
#define HELIX_OLIGO_INDEX_PARITY_FLAG UINT32_C(0x80000000)
#define HELIX_OLIGO_INDEX_KIND_MASK UINT32_C(0xC0000000)
#define HELIX_OLIGO_INDEX_VALUE_MASK UINT32_C(0x3FFFFFFF)
#define HELIX_OLIGO_INDEX_KIND_DATA UINT32_C(0x00000000)
#define HELIX_OLIGO_INDEX_KIND_PARITY_XOR UINT32_C(0x80000000)
#define HELIX_OLIGO_INDEX_KIND_PARITY_GF UINT32_C(0xC0000000)

#define HELIX_CONSTRAINT_GC_MIN_PERCENT 30U
#define HELIX_CONSTRAINT_GC_MAX_PERCENT 70U
#define HELIX_CONSTRAINT_MAX_HOMOPOLYMER 12U

typedef struct {
    uint32_t rs_n;
    uint32_t rs_k;
    uint32_t rs_t;
} helix_config_t;

static inline helix_config_t helix_default_config(void) {
    helix_config_t cfg;
    cfg.rs_n = HELIX_RS_N;
    cfg.rs_k = HELIX_RS_K;
    cfg.rs_t = HELIX_RS_T;
    return cfg;
}

#endif
