#ifndef HELIX_STATUS_H
#define HELIX_STATUS_H

typedef enum {
    HELIX_OK = 0,
    HELIX_ERR_INVALID_ARG = 1,
    HELIX_ERR_FILE_OPEN = 2,
    HELIX_ERR_FILE_READ = 3,
    HELIX_ERR_FILE_WRITE = 4,
    HELIX_ERR_BAD_HEADER = 5,
    HELIX_ERR_INTERNAL = 6,
    HELIX_ERR_BAD_DNA = 7,
    HELIX_ERR_UNCORRECTABLE = 8,
    HELIX_ERR_CHECKSUM = 9,
    HELIX_ERR_BAD_OLIGO = 10,
    HELIX_ERR_CONSTRAINT = 11
} helix_status_t;

#endif
